<template>
  <q-expansion-item
    expand-icon-toggle
    expand-separator
    :icon="docIcon"
    :label="document.metaInfo.title"
    :caption="document.metaInfo.subtitle"
    hide-expand-icon
    v-model="showDocument"
  >
    <template v-slot:header>
      <q-item-section>
        <!--span>
          <q-icon :name="docIcon" />
        </span-->
        <info-viewer
          :meta-info="document?.metaInfo"
          :editable="editable"
          element="documents"
          :element-id="document.id"
          :user-id="userId"
          :show-little="showLittle"
        />
      </q-item-section>
      <q-item-section side top>
        <div>
          <q-btn
            size="sm"
            flat
            round
            dense
            icon="mdi-creation-outline"
            color="primary"
            v-if="editable"
            @click="autoGenerateData()"
          />
          <q-btn
            size="sm"
            flat
            round
            dense
            :icon="showLittle ? 'mdi-unfold-more-horizontal' : 'mdi-unfold-less-horizontal'"
            :color="showLittle ? 'grey' : 'primary'"
            @click="showLittle = !showLittle"
          />
          <q-btn
            size="sm"
            flat
            round
            dense
            :icon="docViewIcon"
            color="grey"
            @click="changeDocView(document.id)"
          />
          <q-btn
            size="sm"
            flat
            round
            dense
            :icon="showDocument ? 'mdi-eye-off-outline' : 'mdi-eye-outline'"
            :color="showDocument ? 'primary' : 'grey'"
            @click="showDocument = !showDocument"
          />
          <q-btn
            size="sm"
            flat
            round
            dense
            color="primary"
            icon="mdi-cloud-download-outline"
            @click="downloadADocument(userId, document.id)"
          />
          <q-btn
            size="sm"
            flat
            round
            dense
            icon="mdi-trash-can-outline"
            color="negative"
            v-if="editable"
            @click="deleteADocument(userId, document.id)"
          />
        </div>
      </q-item-section>
    </template>
    <main-page :url="prepareViewerURL(userId, document.id)" :extension="document.extension" />
  </q-expansion-item>
</template>
<script setup lang="ts">
const props = defineProps({
  document: {
    type: Object as PropType<GSK_DOCUMENT>,
    required: true,
    default: () => ({}),
  },
  editable: {
    type: Boolean,
    required: false,
    default: false,
  },
  idx: {
    type: Number,
    required: false,
    default: -1,
  },
});

import InfoViewer from 'src/components/Users/ViewEdit/Meta/InfoViewer.vue';
import MainPage from 'src/components/Users/ViewEdit/Documents/Viewer/MainPage.vue';

import { computed, type PropType } from 'vue';
import type { GSK_DOCUMENT } from 'src/services/library/types/structures/users';
import { fileIconFromMimeType } from 'src/services/utils/file';
import { downloadADocument, prepareViewerURL } from 'src/services/utils/url';
import { useUsersStore } from 'src/stores/users-store';
import { useSocketStore } from 'src/stores/socket-store';
import { useRoute, useRouter } from 'vue-router';
import type { GSK_CS_DOCUMENT_DELETE_REQUEST } from 'src/services/library/types/data-transfer/documents';
import type { GSK_CS_AI_REQUEST_GEN_DETAILS_FOR_DOC } from 'src/services/library/types/data-transfer/ai';

const usersStore = useUsersStore();
const socketStore = useSocketStore();
const route = useRoute();
const router = useRouter();

const docIcon = computed(() => {
  // Determine icon based on document type or other properties
  return fileIconFromMimeType(props.document.mimeType);
});

const userId = computed(() => {
  return usersStore.getUserIdFromUrlId(route.params.urlUserId as string);
});

const deleteADocument = (userId: string, documentId: string) => {
  const confirm = window.confirm('Are you sure you want to delete this document?');
  if (confirm) {
    const payload: GSK_CS_DOCUMENT_DELETE_REQUEST = {
      id: 'GSK_CS_DOCUMENT_DELETE_REQUEST',
      payload: {
        documentId,
        userId,
      },
    };
    socketStore.emit('GSK_CS_DOCUMENT_DELETE_REQUEST', payload);
  }
};

const showLittle = defineModel('showLittle', {
  type: Boolean,
  required: false,
  default: true,
});
const showDocument = defineModel('showDocument', {
  type: Boolean,
  required: false,
  default: false,
});

const autoGenerateData = () => {
  const confirm = window.confirm(
    'This will generate detailed information for this document using AI and remove the existing data. Do you want to proceed?',
  );
  if (!confirm) return;
  const payload: GSK_CS_AI_REQUEST_GEN_DETAILS_FOR_DOC = {
    id: 'GSK_CS_AI_REQUEST_GEN_DETAILS_FOR_DOC',
    payload: {
      documentId: props.document.id,
      userId: userId.value,
    },
  };
  socketStore.emit('GSK_CS_AI_REQUEST_GEN_DETAILS_FOR_DOC', payload);
};

const viewType = computed(() => {
  const isDocIdInUrl = !!route.params.docId;
  switch (route.name) {
    case 'edit-profile':
    case 'view-profile':
      return 'view-profile';
    case 'view-documents':
    case 'edit-documents':
      return isDocIdInUrl ? 'view-document-item' : 'view-documents';

    default:
      return 'view-documents';
  }
});

const docViewIcon = computed(() => {
  switch (viewType.value) {
    case 'view-document-item':
      return 'mdi-fullscreen-exit';
    default:
      return 'mdi-fullscreen';
  }
});

const changeDocView = async (docId: string) => {
  const isEdit = route.name === 'edit-documents' || route.name === 'edit-profile';
  switch (viewType.value) {
    case 'view-document-item':
      await router.push({
        name: route.name as string,
        params: {
          ...route.params,
          docId: null,
        },
      });
      break;
    case 'view-documents':
      await router.push({
        name: route.name as string,
        params: {
          ...route.params,
          docId: docId,
        },
      });
      break;
    case 'view-profile':
      await router.push({
        name: isEdit ? 'edit-documents' : 'view-documents',
        params: {
          ...route.params,
          docId: docId,
        },
      });
      break;

    default:
      break;
  }
};
</script>
